{% set name = "mando" %}
{% set version = "0.7.1" %}
{% set sha256 = "18baa999b4b613faefb00eac4efadcf14f510b59b924b66e08289aa1de8c3500" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - six
    - python

test:
  imports:
    - mando

about:
  home: https://github.com/rubik/mando
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create Python CLI apps with little to no effort at all!

  description: |
    mando is a wrapper around argparse, and allows you to write complete CLI applications 
    in seconds while maintaining all the flexibility.

extra:
  recipe-maintainers:
    - igortg
